# Generated by Django 2.0.2 on 2018-03-13 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serverML', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='point',
            name='x',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='point',
            name='y',
            field=models.IntegerField(default=0),
        ),
    ]
