# Generated by Django 2.0.2 on 2018-03-13 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('serverML', '0002_auto_20180313_1552'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Point',
            new_name='MyPoint',
        ),
    ]
